- hosts: android-workstation
  tasks:
    - name: Copyfile android-setup.sh to remote machine
      copy: src=android-setup.sh dest=/home/vagrant/ 


    - name: Add permission to android-setup.sh
      shell: chmod +x  /home/vagrant/android-setup.sh

    # - name: Execute setup.sh with arguments
    #   shell: /home/vagrant/setup.sh
    #   register: script_output
    #   changed_when: false

    # - name: Display script output
    #   debug:
    #     var: script_output.stdout_lines
    

    # - name: install packages
    #   apt: name={{item}} state=present
    #   with_items: 
    #     - nodejs
    #     - curl
    #     - wget
    #     - git
    #     - unzip
    #     - yarn
      
    

    